### ISSUE TITLE
7/21/2018 Review Comments

### ISSUE THREAD

**Issue by jawaad-ahmad** [soulzcore/iacc_python_2018#1]
Excellent course, and thank you for taking the time to provide the lecture. A couple comments. Feel free to incorporate or dismiss as you wish.

1. General: Consider avoiding spaces in your MD file names. When trying to follow along with the page shown on the projector, it's helpful to glance in the URL bar to see what page you're presenting so we can follow along, but the %20's can get distracting.

2. Nit: Consider removing the unnecessary semicolons at the end of statements e.g. print statements, variable assignments, etc. The examples in the PEP 8 style guide also don't show such semicolons.

3. Triple-quotes are not multiline comments; they're doc comments that happen to be ignored everywhere else. No need to go into this detail during the course, but best to correct the material by rewording to something such as "Multiline comments can be created by triple quoted strings, but there are some places where triple quoted strings have special meaning" and leave it at that.

4. On *2 - Variables*, Exercise 8, you have the following:

`print(“On ” + todays_date + “the Python class had ” + no_of_students + “ students”)`

Due to the smart quotes, copy/paste fails causing frustration for folks new to programming as well as for QA running through a manual test procedure. Recommend changing to:

`print("On " + todays_date + "the Python class had " + no_of_students + " students")`

5. Also nit on the above - need a space before "the".

6. On *3 - Numbers and Math*, Exercise 2, recommend changing to the following per PEP 8 Pet Peeves:

`print(5>2)`

7. Reminder in *6 - Dictionaries* - Fix typo in Exercise 5 to make "Lemonade" and "Fries" consistent for the example.

8. Nit in Example 7 - same thing about the price of lemonade: There is an inconsistency between 2.5 in the text and 2.25 in the code.

9. Nit in *7 - Sets and Tuples* - Same comment regarding smart quotes in the examples - avoid in example code since we can't copy/paste.

10. Nit: Change "Tupel" to "Tuple".

11. Nit in *8 - Conditional Operators* - Change "statememnts" to "statements".

**Comment by soulzcore** [comment]
Thanks for the comments. Really helpful! I will fix the above and keep others in mind for future sessions.
